# docker-compose.yaml
version: '3'

services:
  recipe-db:
    image: postgres
    container_name: recipe-db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    stdin_open: true
    tty: true
    restart: always    
  web:
    build: '.'
    ports:
      - '5000:5000'
    environment:
      - DB_URL=postgresql://postgres:@recipe-db:5432/postgres  